Proyecto2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('categorias/', include('categorias.urls', namespace="categorias")),
    path('products/', include('products.urls', namespace="products")),
    path('shops/', include('shops.urls', namespace="shops")),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categorias/urls.py
from django.urls import path
from . import views

app_name="categorias"

urlpatterns = [
    path('', views.CategoriaListView.as_view(), name="categoryList"),
    path('crearCategoria/', views.CategoriaCreateView.as_view(), name="categoryCreate"),
    path('<slug:slug>/', views.CategoriaDetailView.as_view(), name="categoryDetail"),
    path('actualizarCategoria/<slug:slug>/', views.CategoriaUpdateView.as_view(), name="categoryUpdate"),
    path('eliminarCategoria/<slug:slug>/', views.CategoriaDeleteView.as_view(), name="categoryDelete"),
]

main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns = [
    path('', views.home, name="home"),
    path('login/',views.loginPage, name="login"),
    path('logout/',views.logoutUser, name="logout"),
    path('register/',views.registerPage, name="register"),
    path("ShoppingCart/",views.ShoppingCart, name="Cart"),
    path('customersupport/',views.CustomerSupportView.as_view(), name="customerSupport"),
    path("AddToCart",views.AddToCart, name="Add"),
]

products/urls.py
from django.urls import path, include   
from . import views

app_name="products"

urlpatterns = [
    path('crearProducto/<str:nombre_tienda>/', views.ProductCreateView.as_view(), name="productCreate"),
    path('detalleProducto/<slug:slug>/', views.ProductDetailView.as_view(), name="productDetail"),
    path('crearResena/<str:nombre_producto>/', views.reviewCreateView.as_view(), name="reviewCreate"),
    path('<slug:categoria_slug>/', views.ProductListView.as_view(), name="productList"),
    path('editarProducto/<slug:slug>/', views.ProductUpdateView.as_view(), name="productUpdate"),
    path('eliminarProducto/<slug:slug>/', views.ProductDeleteView.as_view(), name="productDelete"),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

categorias/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Categoria(models.Model):
    class Meta:
        verbose_name_plural = 'Categorias'
        verbose_name= 'Categoria'

    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    slug = models.SlugField(max_length=50, blank=True, null=True)
    imagen = models.ImageField(upload_to='categorias', blank=True, null=True)

    def save (self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.nombre)
        super(Categoria, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.nombre

products/models.py
from django.db import models
from categorias.models import Categoria
from shops.models import Shop
from django.utils.text import slugify
from django.contrib.auth.models import User
import uuid

# Create your models here.
class Product(models.Model):
    class Meta:
        verbose_name_plural = 'Products'
        verbose_name= 'Product'
    
    name= models.CharField(max_length=255)
    description= models.TextField()
    slug= models.SlugField(max_length=50, blank=True, null=True,unique=True)
    price= models.DecimalField(max_digits=6, decimal_places=2)
    category= models.ForeignKey('categorias.Categoria', on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='products/', blank=True, null=True)
    shop= models.ForeignKey('shops.Shop', on_delete=models.SET_NULL, null=True)

    def save (self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.name} {self.price} {self.category}'
    

class Reviews(models.Model):
    class Meta:
        verbose_name_plural = 'Reviews'
        verbose_name= 'Review'
    

    product= models.ForeignKey(Product, on_delete=models.CASCADE)
    review= models.TextField()
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    created_at= models.DateTimeField(auto_now_add=True)
    score= models.IntegerField()

    # def save (self, *args, **kwargs):
    #     if not self.id:
    #         self.slug = slugify(self.name)
    #     super(Reviews, self).save(*args, **kwargs)


    def __str__(self) -> str:
        return f' {self.review} {self.created_at} {self.score} {self.product}'
    
class Cart (models.Model): 
    id=models.UUIDField(primary_key=True, default=uuid.uuid4)
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    completed= models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)
    
    @property
    def total_price(self):
        cartitems= self.cartitems.all()
        total= sum([item.price for item in cartitems])
        return total
    
    @property
    def num_of_items(self):
        cartitems= self.cartitems.all()
        quantity= sum([item.quantity for item in cartitems])
        return quantity

class CartItem (models.Model):
    product= models.ForeignKey(Product, on_delete=models.CASCADE,related_name='items')
    cart= models.ForeignKey(Cart, on_delete=models.CASCADE,related_name='cartitems')
    quantity= models.IntegerField(default=0)

    def __str__ (self):
        return self.product.name
    
    @property
    def price(self):
        new_price= self.product.price * self.quantity
        return new_price

categorias/forms.py
from dataclasses import field, fields
from django import forms
from django.forms import ModelForm
from .models import Categoria

class CategoriaForm(ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre', 'descripcion', 'imagen']
        labels = {
            'nombre': 'Nombre de la categoria',
            'descripcion': 'Descripcion de la categoria',
            'imagen': 'Imagen de la categoria',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control'}),
            'imagen': forms.FileInput(attrs={'class': 'form-control'}),
        }

categorias/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import redirect
from .models import Categoria
from django.views import generic
from .forms import CategoriaForm
from django.urls import reverse

# Create your views here.
class CategoriaListView(generic.ListView):
    model = Categoria
    template_name = 'categories.html'
    context_object_name = 'categorias'

class CategoriaDetailView(generic.DetailView):
    model = Categoria
    template_name = 'categoryDetail.html'
    context_object_name = 'categoria'

class CategoriaCreateView(generic.CreateView):
    model = Categoria
    template_name = 'categoryCreate.html'
    form_class = CategoriaForm

    def form_valid(self, form):
        return super().form_valid(form)
    
    def get_success_url(self):
        messages.success(self.request, 'Categoria creada con exito')
        return reverse('categorias:categoryList')

class CategoriaUpdateView(generic.UpdateView):
    model = Categoria
    template_name = 'categoryUpdate.html'
    fields = ['nombre', 'descripcion', 'imagen']

    def form_valid(self, form):
        categoria = form.save(commit=False)
        categoria.save()
        messages.success(self.request, 'Categoria actualizada con exito')
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('categorias:categoryList')

class CategoriaDeleteView(generic.DeleteView):
    model = Categoria
    template_name = 'categoryDelete.html'
    context_object_name = 'categoria'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Categoria eliminada con exito')
        return super().delete(request, *args, **kwargs)
    
    def form_valid(self, form):
        messages.success(self.request, 'Categoria eliminada con exito')
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('categorias:categoryList')

categorias/templates/categories.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Categorias{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Categorias</h1>
<br>

<!–- Mostrar datos de la lista -–>
<div class="container">
    {% for categoria in categorias %}

        <a href="{% url 'categorias:categoryDetail' slug=categoria.slug %}">

            <div class="container mx-auto d-flex justify-content-center">
                <div class="card border-dark mb-3" style="width: 20rem; align-items: center; align-self: center;">

                    <!–- Imagen -–>
                    {% if categoria.imagen %}
                        <img src="{{ categoria.imagen.url }}" class="card-img-top" alt="...">
                    {% endif %}

                    <div class="card-body">
                        <h4 class="card-title">{{ categoria.nombre }}</h4>
                        <p class="card-text">{{ categoria.descripcion }}</p> 
                    </div>
                </div>
            </div>

        </a> 

    {% endfor %}

    <!–- Boton para crear una nueva categoria -–>
    <br>
    <div class="d-flex justify-content-center">
        <a href="{% url 'categorias:categoryCreate' %}" class="btn btn-outline-primary">Crear nueva categoria</a>
    </div>
</div>
{% endblock %}

categorias/templates/categoryCreate.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Categorias{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Crear Categoria</h1>
<br>

<!–- Formulario para crear una nueva categoria -–>
<div class="container mx-auto d-flex justify-content-center">
    <form method="POST" enctype="multipart/form-data">
            
        {% csrf_token %}

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Nombre de la categoria</label>
            {{ form.nombre }}
        </div>
    
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Descripcion de la categoria</label>
            {{ form.descripcion }}
        </div>
    
        <div class="mb-3">
            <label for="formFile" class="form-label">Imagen de la categoria</label>
            {{ form.imagen }}
        </div>

        <button type="submit" class="btn btn-outline-success" style="align-self: center;">Crear</button>
    </form>
</div>


{% endblock %}

categorias/templates/categoryDelete.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Categorias{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Eliminar Categoria</h1>
<br>

<!–- Formulario para eliminar una categoria -–>
<form method="POST" enctype="multipart/form-data">

    {% csrf_token %}

    <h5>Estas seguro de eliminar esta categoria?</h5>

    <button type="submit" class="btn btn-danger" style="align-self: center;">Eliminar</button>
    <button class="btn btn-primary" style="align-self: center;">Cancelar</button>
</form>

{% endblock %}

categorias/templates/categoryDetail.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Categorias{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        
        <!–- Titulo -–>
        <h1 class="card-title" style="text-align: center;">{{ categoria.nombre }}</h1>

        <!–- Descripcion -–>
        <p class="card-text" style="text-align: center;">{{ categoria.descripcion }}</p>
    </div>

    <!–- Imagen -–>
    {% if categoria.imagen %}
        <img src="{{ categoria.imagen.url }}" class="rounded mx-auto d-block" alt="..." style="width: 50%; height: 50%;">
    {% endif %}

    <br>

    <!–- Botones -–>
    <div class="d-grid gap-2 d-md-block" style="align-self: center;">
        <!–- Boton para editar una categoria -–>
        <a href="{% url 'categorias:categoryUpdate' slug=categoria.slug %}" class="btn btn-outline-primary">Editar</a>

        <!–- Boton para borrar una categoria -–>
        <a href="{% url 'categorias:categoryDelete' slug=categoria.slug %}" class="btn btn-outline-danger">Eliminar</a>
    </div>

<br>
<!–- Productos -–>
<div class="container">
    <h2 class="display-6">Productos</h2>
    {% for product in categoria.product_set.all %}
    <a href="{% url 'products:productDetail' slug=product.slug %}">
    <div class="card mb-3" style="max-width: 875px;">
        <div class="row g-0">
          <div class="col-md-4">

            <!–- Imagen -–>
            {% if product.imagen %}
              <img src="{{product.imagen.url}}" class="img-fluid rounded-start" alt="...">
            {% endif %}

          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h3 class="card-title">{{product.name}}</h3>
              <p class="card-text">{{product.description}}</p>
              <h4 class="card-text">${{product.price}}</h4>
            </div>
          </div>
        </div>
      </div>
    </a>
    {% endfor %}






</div>


{% endblock %}

categorias/templates/categoryUpdate.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Categorias{% endblock %}

{% block content %}
<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Editar Categoria</h1>
<br>

<!–- Formulario para editar una categoria -–>
<div class="container mx-auto justify-content-center d-flex">
    <form method="post" enctype="multipart/form-data">

        {% csrf_token %}

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Nombre</label>
            {{ form.nombre }}
        </div>

        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Descripcion</label>
            {{ form.descripcion }}
        </div>

        <div class="mb-3">
            <label for="formFile" class="form-label">Imagen</label>
            {{ form.imagen }}
        </div>

        <button type="submit" class="btn btn-outline-success" style="align-self: center;">Editar</button>
    </form>
</div>

{% endblock %}