Proyecto2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('categorias/', include('categorias.urls', namespace="categorias")),
    path('products/', include('products.urls', namespace="products")),
    path('shops/', include('shops.urls', namespace="shops")),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns = [
    path('', views.home, name="home"),
    path('login/',views.loginPage, name="login"),
    path('logout/',views.logoutUser, name="logout"),
    path('register/',views.registerPage, name="register"),
    path("ShoppingCart/",views.ShoppingCart, name="Cart"),
    path('customersupport/',views.CustomerSupportView.as_view(), name="customerSupport"),
    path("AddToCart",views.AddToCart, name="Add"),
]

products/urls.py
from django.urls import path, include   
from . import views

app_name="products"

urlpatterns = [
    path('crearProducto/<str:nombre_tienda>/', views.ProductCreateView.as_view(), name="productCreate"),
    path('detalleProducto/<slug:slug>/', views.ProductDetailView.as_view(), name="productDetail"),
    path('crearResena/<str:nombre_producto>/', views.reviewCreateView.as_view(), name="reviewCreate"),
    path('<slug:categoria_slug>/', views.ProductListView.as_view(), name="productList"),
    path('editarProducto/<slug:slug>/', views.ProductUpdateView.as_view(), name="productUpdate"),
    path('eliminarProducto/<slug:slug>/', views.ProductDeleteView.as_view(), name="productDelete"),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

shops/urls.py
from django.urls import path
from . import views

app_name="shops"

urlpatterns = [
    path('', views.ShopListView.as_view(), name="shopList"),
    path('crearTienda/', views.ShopCreateView.as_view(), name="shopCreate"),
    path('<slug:slug>/', views.ShopDetailView.as_view(), name="shopDetail"),
    path('crearResena/<str:nombre_tienda>/', views.reviewShopCreateView.as_view(), name="reviewShopCreate"),
    path('AdministrarTienda/<slug:slug>/', views.ShopAdminView.as_view(), name="shopAdmin"),
    path('actualizarTienda/<slug:slug>/', views.ShopUpdateView.as_view(), name="shopUpdate"),
    #path('eliminarTienda/<slug:slug>/', views.ShopDeleteView.as_view(), name="shopDelete"),
]

products/models.py
from django.db import models
from categorias.models import Categoria
from shops.models import Shop
from django.utils.text import slugify
from django.contrib.auth.models import User
import uuid

# Create your models here.
class Product(models.Model):
    class Meta:
        verbose_name_plural = 'Products'
        verbose_name= 'Product'
    
    name= models.CharField(max_length=255)
    description= models.TextField()
    slug= models.SlugField(max_length=50, blank=True, null=True,unique=True)
    price= models.DecimalField(max_digits=6, decimal_places=2)
    category= models.ForeignKey('categorias.Categoria', on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='products/', blank=True, null=True)
    shop= models.ForeignKey('shops.Shop', on_delete=models.SET_NULL, null=True)

    def save (self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.name} {self.price} {self.category}'
    

class Reviews(models.Model):
    class Meta:
        verbose_name_plural = 'Reviews'
        verbose_name= 'Review'
    

    product= models.ForeignKey(Product, on_delete=models.CASCADE)
    review= models.TextField()
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    created_at= models.DateTimeField(auto_now_add=True)
    score= models.IntegerField()

    # def save (self, *args, **kwargs):
    #     if not self.id:
    #         self.slug = slugify(self.name)
    #     super(Reviews, self).save(*args, **kwargs)


    def __str__(self) -> str:
        return f' {self.review} {self.created_at} {self.score} {self.product}'
    
class Cart (models.Model): 
    id=models.UUIDField(primary_key=True, default=uuid.uuid4)
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    completed= models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)
    
    @property
    def total_price(self):
        cartitems= self.cartitems.all()
        total= sum([item.price for item in cartitems])
        return total
    
    @property
    def num_of_items(self):
        cartitems= self.cartitems.all()
        quantity= sum([item.quantity for item in cartitems])
        return quantity

class CartItem (models.Model):
    product= models.ForeignKey(Product, on_delete=models.CASCADE,related_name='items')
    cart= models.ForeignKey(Cart, on_delete=models.CASCADE,related_name='cartitems')
    quantity= models.IntegerField(default=0)

    def __str__ (self):
        return self.product.name
    
    @property
    def price(self):
        new_price= self.product.price * self.quantity
        return new_price

products/forms.py
from django import forms
from django.forms import ModelForm
from .models import Product, Reviews
from categorias.models import Categoria

class ProductsForm(ModelForm):
    model= Product
    fields= ['name', 'description', 'price', 'category', 'imagen', 'shop']
    labels= {
        'name': 'Nombre del producto',
        'description': 'Descripcion del producto',
        'price': 'Precio del producto',
        'category': 'Categoria del producto',
        'imagen': 'Imagen del producto',
        'shop': 'Tienda',
    }
    widgets= {
        'name': forms.TextInput(attrs={'class': 'form-control'}),
        'description': forms.Textarea(attrs={'class': 'form-control'}),
        'price': forms.NumberInput(attrs={'class': 'form-control', 'min': 0, 'max': 10000}),
        'category': forms.Select(attrs={'class': 'form-control'}),
        'imagen': forms.FileInput(attrs={'class': 'form-control'}),
        'shop': forms.Select(attrs={'class': 'form-control'}),
    }

class ReviewForm(ModelForm):
    class Meta:
        model= Reviews
        fields= ['review', 'score']

    
    labels= {
        'review': 'Escribe tu reseña',
        'score': 'Calificacion',
    }


    widgets= {
        'review': forms.Textarea(attrs={'class': 'form-control'}),
        'score': forms.IntegerField(widget=forms.NumberInput(attrs={'min': 1, 'max': 5})),
    }

products/views.py
from django.shortcuts import render
from .models import Product, Reviews
from .forms import ReviewForm
from categorias.models import Categoria
from shops.models import Shop
from django.views import generic
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404, render


# Create your views here.
class ProductListView(generic.ListView):
    model = Product
    template_name = 'products.html'
    context_object_name = 'products'

    def get_queryset(self):
        categoria_slug = self.kwargs['categoria_slug']
        categoria = Categoria.objects.get(slug=categoria_slug)
        return Product.objects.filter(categoria=categoria)

class ProductCreateView(generic.CreateView):
    model = Product
    template_name = 'productCreate.html'
    fields = ['name', 'description', 'price', 'category', 'imagen']

    def get_context_data(self, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context['shop'] = Shop.objects.get(slug=self.kwargs['nombre_tienda'])
        print(context['shop'])
        return context
    
    def form_valid(self, form):
        form.instance.shop= Shop.objects.get(slug=self.kwargs['nombre_tienda'])
        form.instance.user= self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('categorias:categoryList')
    
class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'productDetail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.object  
        reviews = Reviews.objects.filter(product=product) 
        context['shop'] = self.object.shop
        context['reviews'] = reviews
        return context
    
   

class reviewCreateView(generic.CreateView):
    model = Reviews
    template_name = 'review.html'
    form_class = ReviewForm

    def get_context_data(self, **kwargs):
        context = super(reviewCreateView, self).get_context_data(**kwargs)
        context['product'] = Product.objects.get(slug=self.kwargs['nombre_producto'])
        print(context['product'])
        return context
    
    def form_valid(self, form):
        form.instance.product= Product.objects.get(slug=self.kwargs['nombre_producto'])
        form.instance.user= self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('categorias:categoryList')

class reviewListView(generic.ListView):
    model = Reviews
    template_name = 'productDetail.html'
    context_object_name = 'reviews'

class ProductUpdateView (generic.UpdateView):
    model = Product
    template_name = 'productUpdate.html'
    fields = ['name', 'description', 'price', 'category', 'imagen']

    def form_valid(self, form):
        product = form.save(commit=False)
        product.save()
        messages.success(self.request, 'Producto editado con exito')
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('categorias:categoryList')
    
class ProductDeleteView (generic.DeleteView):
    model = Product
    template_name = 'productDelete.html'
    context_object_name = 'product'

    def get_success_url(self):
        return reverse('categorias:categoryList')
    

products/templates/productCreate.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Productos{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Agregar Producto</h1>
<br>

<!–- Formulario para agregar un nuevo producto -–>
<div class="container d-flex mx-auto justify-content-center">
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Nombre del producto</label>
            {{ form.name }}
        </div>
    
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Descripcion del producto</label>
            {{ form.description }}
        </div>

        <label for="exampleFormControlTextarea1" class="form-label">Precio</label>
        <div class="input-group mb-3">
            <span class="input-group-text">$</span>
            {{ form.price }}
            <span class="input-group-text"></span>
        </div>

        <label for="exampleFormControlTextarea1" class="form-label">Categoria</label>
        {{ form.category }}

        <label for="formFile" class="form-label">Imagen del producto</label>
        <div class="mb-3">
            {{ form.imagen }}
        </div>

        {{ form.shop }}

        <button type="submit" class="btn btn-outline-success" style="align-self: center;">Agregar</button>
    </form>
</div>

{% endblock %}

products/templates/productDelete.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Productos{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Eliminar Producto</h1>
<br>

<!–- Formulario para eliminar una categoria -–>
<div class="container mx-auto d-flex justify-content-center">
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
    
        <h5>Estas seguro de eliminar este producto?</h5>
        <br>

        <div class="container mx-auto d-flex justify-content-center">
            <button type="submit" class="btn btn-outline-danger" style="align-self: center;">Eliminar</button>
            <button class="btn btn-outline-primary m-2" style="align-self: center;">Cancelar</button>
        </div>
    </form>
</div>

{% endblock %}

products/templates/productDetail.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Producto{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
<div class="container">

  <!–-Productos-–>
  <div class="card mb-3" style="max-width: 900px;">
    <div class="row g-0">
      <div class="col-md-4">

        <!–- Imagen -–>
        {% if product.imagen %}
          <img src="{{product.imagen.url}}" class="card-img-top" alt="...">
        {% endif %}
      </div>

      <div class="col-md-8">
        <div class="card-body">

          <!–- Nombre, descripcion, precio y vendedor -–>
          <h3 class="card-title">{{product.name}}</h3>
          <p class="card-text">{{product.description}}</p>
          <a href="{% url 'shops:shopDetail' slug=shop.slug %}"<h6 class="card-title"> Vendido por: {{product.shop}} <br></h6></a>
          <br>
          <h4 class="card-title">Precio: ${{product.price}}</h4>
      
          <!–- Boton para agregar al carrito-–>
          <button class="btn btn-outline-primary" value="{{ product.id }}" style="width: 400px; margin-left: 14%; background-color: #7cffc4; border-color: #7cffc4;">Agregar al carrito</button>
          <br>

            {% if product.shop == user.shop %}

              <br>
              <!–- Boton para editar-–>
              <a href="{% url 'products:productUpdate' slug=product.slug %}" class="btn btn-outline-primary" style="width: 190px; margin-left: 14%;">Editar</a>
              
              <!–- Boton para eliminar-–>
              <a href="{% url 'products:productDelete' slug=product.slug %}" class="btn btn-outline-danger" style="width: 190px; margin-left: 3%;">Eliminar</a>
              <br>
            {% endif %}

            <!------------- PAYPAL BUTTONS HERE  --------------------->
            <br>
          <div id="paypal-button-container" style="width: 400px; margin-left: 14%;"></div>
          
            <!-- Include the PayPal JavaScript SDK -->
            <script
              src="https://www.paypal.com/sdk/js?client-id=AQ7rlKgckBWsOiilQiRfBw4FCeXtuDztA__MSSnS8RYwVa_nilupSjXqWeRmr5Zu7Q53sb1kTtWoEtXn&currency=USD"></script>
          
            <script>
            // Render the PayPal button into #paypal-button-container
              paypal.Buttons({

                // Set up the transaction
                createOrder: function (data, actions) {
                  return actions.order.create({
                    purchase_units: [{
                      amount: {
                        value: '{{ product.price }}'
                    }
                  }]
                });
              },

                // Finalize the transaction
                onApprove: function (data, actions) {
                  return actions.order.capture().then(function (details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name
                      .given_name + '!');
                  });
                }
              }).render('#paypal-button-container');
            </script>
          </div>
          <!------------- PAYPAL BUTTONS HERE  --------------------->

        </div>
      </div>
    </div>
  </div>
  <br>

  <!–- Reviews-–>
  <br>
  <div class="container">
    <h3 class="display-6">Reviews</h3>

    {% for review in reviews %}

    <div class="card">
      <div class="card-body" style="background-color: #b4cded;">
        <h5 class="card-title">Puntaje: {{ review.score }} / {{ review.review }}</h5>
        <p class="card-text">Review creada por: {{ review.user }}</p>
        <p class="card-text"><small class="text-body-secondary">{{ review.created_at }}</small></p>
      </div>
    </div>
    <br>
    
    {% endfor %}
    
  </div>
  <div class="container">
  <!–- Boton para hacer reviews-–>
  <a href="{% url 'products:reviewCreate' nombre_producto=product.slug %}" class="btn btn-outline-primary" style="margin-left: 185px; margin-bottom: 20px;">Hacer Review</a>
  </div>

</div>

{% endblock %}
    

products/templates/productUpdate.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Productos{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Editar Producto</h1>
<br>

<!–- Formulario -–>
<div class="container mx-auto d-flex justify-content-center">
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
    
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Nombre del producto</label>
            {{ form.name }}
        </div>
    
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Descripcion del producto</label>
            {{ form.description }}
        </div>

        <div class="input-group mb-3">
            <span class="input-group-text">$</span>
            {{ form.price }}
            <span class="input-group-text"></span>
        </div>

        {{ form.category }}

        <div class="mb-3">
            <label for="formFile" class="form-label">Imagen del producto</label>
            {{ form.imagen }}
        </div>
    
        <button type="submit" class="btn btn-outline-success" style="align-self: center;">Editar</button>
    </form>
</div>

{% endblock %}

products/templates/review.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Review{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Hacer Review</h1>
<br>

<!–- Formulario para hacer review -–>
<div class="container mx-auto d-flex justify-content-center">
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Review</label>
            {{ form.review }}
        </div>
    
        <div class="input-group mb-3">
            <span class="input-group-text">⭐</span>
            {{ form.score }}
            <span class="input-group-text"></span>
        </div>
        <button type="submit" class="btn btn-outline-success" style="align-self: center;">Crear</button>
    </form>
</div>

{% endblock %}