Proyecto2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('categorias/', include('categorias.urls', namespace="categorias")),
    path('products/', include('products.urls', namespace="products")),
    path('shops/', include('shops.urls', namespace="shops")),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categorias/urls.py
from django.urls import path
from . import views

app_name="categorias"

urlpatterns = [
    path('', views.CategoriaListView.as_view(), name="categoryList"),
    path('crearCategoria/', views.CategoriaCreateView.as_view(), name="categoryCreate"),
    path('<slug:slug>/', views.CategoriaDetailView.as_view(), name="categoryDetail"),
    path('actualizarCategoria/<slug:slug>/', views.CategoriaUpdateView.as_view(), name="categoryUpdate"),
    path('eliminarCategoria/<slug:slug>/', views.CategoriaDeleteView.as_view(), name="categoryDelete"),
]

main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns = [
    path('', views.home, name="home"),
    path('login/',views.loginPage, name="login"),
    path('logout/',views.logoutUser, name="logout"),
    path('register/',views.registerPage, name="register"),
    path("ShoppingCart/",views.ShoppingCart, name="Cart"),
    path('customersupport/',views.CustomerSupportView.as_view(), name="customerSupport"),
    path("AddToCart",views.AddToCart, name="Add"),
]

shops/urls.py
from django.urls import path
from . import views

app_name="shops"

urlpatterns = [
    path('', views.ShopListView.as_view(), name="shopList"),
    path('crearTienda/', views.ShopCreateView.as_view(), name="shopCreate"),
    path('<slug:slug>/', views.ShopDetailView.as_view(), name="shopDetail"),
    path('crearResena/<str:nombre_tienda>/', views.reviewShopCreateView.as_view(), name="reviewShopCreate"),
    path('AdministrarTienda/<slug:slug>/', views.ShopAdminView.as_view(), name="shopAdmin"),
    path('actualizarTienda/<slug:slug>/', views.ShopUpdateView.as_view(), name="shopUpdate"),
    #path('eliminarTienda/<slug:slug>/', views.ShopDeleteView.as_view(), name="shopDelete"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    class Meta:
        verbose_name_plural = 'User Profiles'
        verbose_name= 'User Profile'
    
    user= models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.user.first_name} {self.user.last_name}'

class CustomerSupport(models.Model):
    class Meta:
        verbose_name_plural = 'Customer Support'
        verbose_name= 'Customer Support'

    name= models.CharField(max_length=50, blank=True, null=True)
    phone= models.CharField(max_length=10)
    email= models.EmailField(max_length=50)
    message= models.TextField(max_length=500)

main/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import CustomerSupport

class CreateUserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email', 'password1','password2']


class LoginForm(AuthenticationForm):
    class Meta:
        model=User
        fields=['username','password']

class CustomerSupportForm(ModelForm):
    class Meta:
        model = CustomerSupport
        fields = ['name','phone', 'email', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'message': forms.Textarea(attrs={'class': 'form-control'}),
        }

main/views.py
from django.views import generic
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth import authenticate,login,logout
from .forms import CreateUserForm, LoginForm
from categorias.models import Categoria
from .models import CustomerSupport
from products.models import Product, CartItem, Cart
from django.http import JsonResponse
import json

# Create your views here.
def home(request):
    category = Categoria.objects.all()
    products = Product.objects.all()[3:]
    return render(request, 'main/home.html', {'category':category, 'products':products})

class ProductHomeListView(generic.ListView):
    model = Product
    template_name = 'home.html'
    context_object_name = 'products'

    def get_queryset(self):
     return Product.objects.all()[:3]

def loginPage(request):
    error = None

    if request.user.is_authenticated:
        return redirect("main:home")
    else:
        if request.method == 'POST':
            username= request.POST.get('username')
            password= request.POST.get('password')

            user= authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("main:home")
            else:
                error = 'Usuario o contraseña incorrecta'
        context={'error':error}
        return render(request, 'main/registration/login.html',context)
    

def logoutUser(request):
    logout(request)
    return redirect("main:login")

def registerPage(request):
    if request.user.is_authenticated:
        return redirect("main:home")
    else:
        form= CreateUserForm()
        if request.method == 'POST':
            form= CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user =  form.cleaned_data.get('username')
                messages.success(request, 'Account was created for' + user)

                return redirect('main:login')
            
        context = {'form':form}
        return render(request, 'main/registration/register.html',context)

class CustomerSupportView(generic.CreateView):
    model = CustomerSupport
    fields = ['name', 'phone','email', 'message']
    template_name = 'main/customersupport.html'
    success_url = '/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

def ShoppingCart (request):
    cart=None
    cartitems= []

    if request.user.is_authenticated:
        cart, created= Cart.objects.get_or_create(user=request.user, completed=False)
        cartitems= cart.cartitems.all()

    context = {"cart":cart, "items":cartitems}
    return render(request, 'main/ShoppingCart.html', context)

def AddToCart (request):
    data=json.loads(request.body)
    product_id= data["id"]
    product= Product.objects.get(id=product_id)

    if request.user.is_authenticated:
        cart, created= Cart.objects.get_or_create(user=request.user, completed=False)
        cartitem, created= CartItem.objects.get_or_create(cart=cart, product=product)
        cartitem.quantity +=1
        cartitem.save()
        num_of_items= cart.num_of_items
        print(cartitem)
        
    return JsonResponse(num_of_items, safe=False)

main/templates/main/partials/footer.html
{% load static %}
<!-- ================================
Start Footer
================================= -->

<!-- Footer -->
<footer class="bg-dark text-center text-lg-start">
    <!-- Copyright -->
    <div class="text-center p-3 text-light">
      © 2023 Copyright:
      <a class="text-light" href="https://mdbootstrap.com/">SHADOW WIZARD MONEY GANG</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

main/templates/main/partials/navbar.html
{% load static %}
<header>
  <nav class="navbar bg-body-tertiary fixed-top stick-top" style="background-color: #344966; color: white;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'main:home' %}">Los Dealers Store</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"><img src="{% static 'images/menu-hamburguesa-blanco.png' %}" class="d-block w-100" alt="..."></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel" style="color: #344966;">Los Dealers Store</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'main:home' %}" style="color: #344966;">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'main:customerSupport' %}" style="color: #344966;">Atencion al cliente</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" href="{% url 'categorias:categoryList' %}" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: #344966;">
                Ver
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item" href="{% url 'categorias:categoryList' %}" style="color: #344966;">Categorias</a></li>
                <li><a class="dropdown-item" href="{% url 'shops:shopList' %}" style="color: #344966;">Tiendas </a></li>
              </ul>
            </li>

            {% if user.is_authenticated %}
             <li class="nav-item">
              <a class="nav-link active" href="{% url 'main:Cart' %}" style="color: #344966;">Carrito de Compras {{ cart.num_of_items }}</a>
            </li>
            {% if user.shop %}
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'shops:shopAdmin' slug=user.shop.slug %}" style="color: #344966;">Administrar Tienda</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'shops:shopCreate' %}" style="color: #344966;">Crear Tienda</a>
            </li>
            {% endif %}
             <li class="nav-item">
              <a class="nav-link active" href="{% url 'main:logout' %}" tabindex="-1" aria-disabled="true" style="color: #344966;">Salir</a>
            </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'main:login' %}" tabindex="-1" aria-disabled="true" style="color: #344966;">Login</a>
              </li>
              {% endif %}

          </ul>
        </div>
      </div>
    </div>
  </nav>
  <br>
  <br>
</header>