Proyecto2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('categorias/', include('categorias.urls', namespace="categorias")),
    path('products/', include('products.urls', namespace="products")),
    path('shops/', include('shops.urls', namespace="shops")),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns = [
    path('', views.home, name="home"),
    path('login/',views.loginPage, name="login"),
    path('logout/',views.logoutUser, name="logout"),
    path('register/',views.registerPage, name="register"),
    path("ShoppingCart/",views.ShoppingCart, name="Cart"),
    path('customersupport/',views.CustomerSupportView.as_view(), name="customerSupport"),
    path("AddToCart",views.AddToCart, name="Add"),
]

products/urls.py
from django.urls import path, include   
from . import views

app_name="products"

urlpatterns = [
    path('crearProducto/<str:nombre_tienda>/', views.ProductCreateView.as_view(), name="productCreate"),
    path('detalleProducto/<slug:slug>/', views.ProductDetailView.as_view(), name="productDetail"),
    path('crearResena/<str:nombre_producto>/', views.reviewCreateView.as_view(), name="reviewCreate"),
    path('<slug:categoria_slug>/', views.ProductListView.as_view(), name="productList"),
    path('editarProducto/<slug:slug>/', views.ProductUpdateView.as_view(), name="productUpdate"),
    path('eliminarProducto/<slug:slug>/', views.ProductDeleteView.as_view(), name="productDelete"),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

shops/urls.py
from django.urls import path
from . import views

app_name="shops"

urlpatterns = [
    path('', views.ShopListView.as_view(), name="shopList"),
    path('crearTienda/', views.ShopCreateView.as_view(), name="shopCreate"),
    path('<slug:slug>/', views.ShopDetailView.as_view(), name="shopDetail"),
    path('crearResena/<str:nombre_tienda>/', views.reviewShopCreateView.as_view(), name="reviewShopCreate"),
    path('AdministrarTienda/<slug:slug>/', views.ShopAdminView.as_view(), name="shopAdmin"),
    path('actualizarTienda/<slug:slug>/', views.ShopUpdateView.as_view(), name="shopUpdate"),
    #path('eliminarTienda/<slug:slug>/', views.ShopDeleteView.as_view(), name="shopDelete"),
]

products/models.py
from django.db import models
from categorias.models import Categoria
from shops.models import Shop
from django.utils.text import slugify
from django.contrib.auth.models import User
import uuid

# Create your models here.
class Product(models.Model):
    class Meta:
        verbose_name_plural = 'Products'
        verbose_name= 'Product'
    
    name= models.CharField(max_length=255)
    description= models.TextField()
    slug= models.SlugField(max_length=50, blank=True, null=True,unique=True)
    price= models.DecimalField(max_digits=6, decimal_places=2)
    category= models.ForeignKey('categorias.Categoria', on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='products/', blank=True, null=True)
    shop= models.ForeignKey('shops.Shop', on_delete=models.SET_NULL, null=True)

    def save (self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.name} {self.price} {self.category}'
    

class Reviews(models.Model):
    class Meta:
        verbose_name_plural = 'Reviews'
        verbose_name= 'Review'
    

    product= models.ForeignKey(Product, on_delete=models.CASCADE)
    review= models.TextField()
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    created_at= models.DateTimeField(auto_now_add=True)
    score= models.IntegerField()

    # def save (self, *args, **kwargs):
    #     if not self.id:
    #         self.slug = slugify(self.name)
    #     super(Reviews, self).save(*args, **kwargs)


    def __str__(self) -> str:
        return f' {self.review} {self.created_at} {self.score} {self.product}'
    
class Cart (models.Model): 
    id=models.UUIDField(primary_key=True, default=uuid.uuid4)
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    completed= models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)
    
    @property
    def total_price(self):
        cartitems= self.cartitems.all()
        total= sum([item.price for item in cartitems])
        return total
    
    @property
    def num_of_items(self):
        cartitems= self.cartitems.all()
        quantity= sum([item.quantity for item in cartitems])
        return quantity

class CartItem (models.Model):
    product= models.ForeignKey(Product, on_delete=models.CASCADE,related_name='items')
    cart= models.ForeignKey(Cart, on_delete=models.CASCADE,related_name='cartitems')
    quantity= models.IntegerField(default=0)

    def __str__ (self):
        return self.product.name
    
    @property
    def price(self):
        new_price= self.product.price * self.quantity
        return new_price

shops/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
# Create your models here.
class Shop(models.Model):
    class Meta:
        verbose_name_plural = 'Shops'
        verbose_name= 'Shop'

    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, blank=True, null=True)
    score = models.IntegerField(default=0)
    imagen = models.ImageField(upload_to='shops/', blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    def save (self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Shop, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name    
    
class ReviewShop(models.Model):
    class Meta:
        verbose_name_plural = 'ReviewsShop'
        verbose_name= 'ReviewShop'
    

    shop= models.ForeignKey(Shop, on_delete=models.CASCADE)
    review= models.TextField()
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    created_at= models.DateTimeField(auto_now_add=True)
    score= models.IntegerField()


    def __str__(self) -> str:
        return f' {self.review} {self.created_at} {self.score} {self.shop}'

shops/forms.py
from django import forms
from django.forms import ModelForm
from .models import Shop,ReviewShop

class ShopForm(ModelForm):
    class Meta:
        model= Shop
        fields= ['name', 'imagen']
    labels= {
        'name': 'Dale un nombre a la tienda',
        'imagen': 'Imagen del producto',
    }
    widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'imagen': forms.FileInput(attrs={'class': 'form-control'}),
        }
    
class ReviewShopForm(ModelForm):
    class Meta:
        model= ReviewShop
        fields= ['review', 'score']

    
    labels= {
        'review': 'Escribe tu reseña',
        'score': 'Calificacion',
    }


    widgets= {
        'review': forms.Textarea(attrs={'class': 'form-control'}),
        'score': forms.IntegerField(widget=forms.NumberInput(attrs={'min': 1, 'max': 5})),
    }

shops/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib import messages
from django.urls import reverse
from .models import Shop, ReviewShop
from .forms import ShopForm, ReviewShopForm
from django.db import models
# Create your views here.
class ShopListView(generic.ListView):
    model = Shop
    template_name = 'shopList.html'
    context_object_name = 'shops'

    def get_queryset(self):
        return Shop.objects.all()
class ShopCreateView(generic.CreateView):
    model = Shop
    template_name = 'shopCreate.html'
    form_class = ShopForm
    
    def form_valid(self, form):
        shop = form.save(commit=False)
        shop.user = self.request.user
        shop.save()
        messages.success(self.request, 'Tienda agregada con exito')
        return super().form_valid(form)
    
    def form_valid(self, form):
        form.instance.user= self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('main:home')
    
class ShopUpdateView(generic.UpdateView):
    model = Shop
    template_name = 'shopUpdate.html'
    form_class = ShopForm

    def get_success_url(self):
        return reverse('main:home')

class ShopDetailView(generic.DetailView):
    model = Shop
    template_name = 'shopDetail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        shop = self.object  
        reviews = ReviewShop.objects.filter(shop=shop) 
        context['reviewShop'] = reviews
        return context
    
class reviewShopCreateView(generic.CreateView):
    model = ReviewShop
    template_name = 'reviewShop.html'
    form_class = ReviewShopForm

    def get_context_data(self, **kwargs):
        context = super(reviewShopCreateView, self).get_context_data(**kwargs)
        context['shop'] = Shop.objects.get(slug=self.kwargs['nombre_tienda'])
        return context
    
    def form_valid(self, form):
        form.instance.user= self.request.user
        form.instance.shop= Shop.objects.get(slug=self.kwargs['nombre_tienda'])
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('main:home')

class reviewShopListView(generic.ListView):
    model = ReviewShop
    template_name = 'shopDetail.html'
    context_object_name = 'reviewShop'

class ShopAdminView(generic.DetailView):
    model = Shop
    template_name = 'shopAdmin.html'
    context_object_name = 'shop'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        shop = self.object  
        reviews = ReviewShop.objects.filter(shop=shop) 
        context['reviewShop'] = reviews
        return context
    

shops/templates/reviewShop.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Review{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Hacer Review</h1>
<br>

<!–- Formulario para hacer review -–>
<div class="container mx-auto d-flex justify-content-center">
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Review</label>
            {{ form.review }}
        </div>
    
        <div class="input-group mb-3">
            <span class="input-group-text">⭐</span>
            {{ form.score }}
            <span class="input-group-text"></span>
        </div>
        <button type="submit" class="btn btn-outline-success" style="align-self: center;">Crear</button>
    </form>
</div>



{% endblock %}

shops/templates/shopAdmin.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Tienda{% endblock %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Administrar tienda</h1>
<br>

{% block content %}
<div class="card">
    <div class="card-body">
        
        <!–- Titulo -–>
        <h1 class="card-title" style="text-align: center;">{{ shop.name}}</h1>

    </div>

    <!–- Imagen -–>
    {% if shop.imagen %}
        <img src="{{ shop.imagen.url }}" class="rounded mx-auto d-block" alt="..." style="width: 50%; height: 50%;">
    {% endif %}
</div>
<div class="container">
    <!–- Boton para editar-–>
    <a href="{% url 'shops:shopUpdate' slug=shop.slug %}" class="btn btn-outline-primary">Editar</a>
    <br>
</div>

    <br>


  
<br>
<!–- Productos -–>
<div class="container">
    <br>
    <h2 class="display-6">Productos</h2>
    {% for product in shop.product_set.all %}
    <a href="{% url 'products:productDetail' slug=product.slug %}">
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">

            <!–- Imagen -–>
            {% if product.imagen %}
              <img src="{{product.imagen.url}}" class="img-fluid rounded-start" alt="...">
            {% endif %}

          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{product.name}}</h5>
              <p class="card-text">{{product.description}}</p>
              <p class="card-text"><small class="text-body-secondary">{{product.price}}</small></p>
            </div>
          </div>
        </div>
      </div>
    </a>
    {% endfor %}
    <!–- Boton para agregar productos-–>
    <a href="{% url 'products:productCreate' nombre_tienda=shop.slug %}" class="btn btn-outline-primary">Agregar Producto</a>

    <!–- Reviews-–>
    <br>
    <h3 class="display-6">Reviews</h3>
    {% for review in reviewShop %}
    <div class="card mb-3" >
      <div class="card-body">
        <!--<h5 class="card-title">Card title</h5>-->
        <h6 class="card-subtitle mb-2 text-body-secondary">Puntaje: {{review.score}}</h6>
        <p class="card-text">{{ review.review}}</p>
        <h6 class="card-subtitle mb-2 text-body-secondary">Review creada por: {{review.user}}</h6>
        <p class="card-text"><small class="text-body-secondary">{{review.created_at}}</small></p>
        <!--<a href="#" class="card-link">Car</a>-->
      </div>
    </div>
    {% endfor %}
    <br>



    {% endblock %}

shops/templates/shopCreate.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Categorias{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Crear Tienda</h1>
<br>

<!–- Formulario para crear una nueva tienda -–>
<div class="container mx-auto d-flex justify-content-center">
    <form method="POST" enctype="multipart/form-data">
            
        {% csrf_token %}

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Nombre de la tienda</label>
            {{ form.name }}
        </div>
    

    
        <div class="mb-3">
            <label for="formFile" class="form-label">Imagen de la categoria</label>
            {{ form.imagen }}
        </div>

        <button type="submit" class="btn btn-outline-success" style="align-self: center;">Crear</button>
    </form>
</div>


{% endblock %}

shops/templates/shopDetail.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Tienda{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        
        <!–- Titulo -–>
        <h1 class="card-title" style="text-align: center;">{{ shop.name}}</h1>

    </div>

    <!–- Imagen -–>
    {% if shop.imagen %}
        <img src="{{ shop.imagen.url }}" class="rounded mx-auto d-block" alt="..." style="width: 50%; height: 50%;">
    {% endif %}
    


  
<br>
<!–- Productos -–>
<div class="container">
    <br>
    <h2 class="display-6">Productos</h2>
    {% for product in shop.product_set.all %}
    <a href="{% url 'products:productDetail' slug=product.slug %}">
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
          <div class="col-md-4">

            <!–- Imagen -–>
            {% if product.imagen %}
              <img src="{{product.imagen.url}}" class="img-fluid rounded-start" alt="...">
            {% endif %}

          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">{{product.name}}</h5>
              <p class="card-text">{{product.description}}</p>
              <p class="card-text"><small class="text-body-secondary">{{product.price}}</small></p>
            </div>
          </div>
        </div>
      </div>
    </a>
    {% endfor %}

    <!–- Reviews-–>
    <br>
    <h3 class="display-6">Reviews</h3>
    {% for review in reviewShop %}
    <div class="card mb-3" >
      <div class="card-body"  style="background-color: #b4cded;">
        <!--<h5 class="card-title">Card title</h5>-->
        <h6 class="card-subtitle mb-2 text-body-secondary">Puntaje: {{review.score}}</h6>
        <p class="card-text">{{ review.review}}</p>
        <h6 class="card-subtitle mb-2 text-body-secondary">Review creada por: {{review.user}}</h6>
        <p class="card-text"><small class="text-body-secondary">{{review.created_at}}</small></p>
        <!--<a href="#" class="card-link">Car</a>-->
      </div>
    </div>
    {% endfor %}
    <br>

    <!–- Boton para hacer reviews-–>
    <a href="{% url 'shops:reviewShopCreate' nombre_tienda=shop.slug %}" class="btn btn-outline-primary">Hacer Review</a>

    {% endblock %}

shops/templates/shopList.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Categorias{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Tiendas</h1>
<br>

<!–- Mostrar datos de la lista -–>
<div class="container">
    {% for shop in shops %}

        <a href="{% url 'shops:shopDetail' slug=shop.slug %}">

            <div class="container mx-auto d-flex justify-content-center" >
                <div class="card border-dark mb-3" style="width: 20rem; align-items: center; align-self: center;">

                    <!–- Imagen -–>
                    {% if shop.imagen %}
                        <img src="{{ shop.imagen.url }}" class="card-img-top" alt="...">
                    {% endif %}

                    <div class="card-body">
                        <h4 class="card-title">{{ shop.name }}</h4> 
                    </div>
                </div>
            </div>

        </a> 

    {% endfor %}
{% endblock %}

shops/templates/shopUpdate.html
<!–- Cargar css y extras -–>
{% extends 'main/base.html' %}
{% load static %}
{% block title %}Tienda{% endblock %}

{% block content %}

<!–- Titulo -–>
<br>
    <h1 style="text-align:center">Crear Tienda</h1>
<br>

<!–- Formulario para actualizar una para tienda -–>
<div class="container mx-auto d-flex justify-content-center">
    <form method="POST" enctype="multipart/form-data">
            
        {% csrf_token %}

        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Nombre de la tienda</label>
            {{ form.name }}
        </div>
    

    
        <div class="mb-3">
            <label for="formFile" class="form-label">Imagen de la tienda</label>
            {{ form.imagen }}
        </div>

        <button type="submit" class="btn btn-outline-success" style="align-self: center;">Actualizar</button>
    </form>
</div>


{% endblock %}